"""Realistic fixture contents of /etc/resolv.conf for parser tests."""

TYPICAL_RESOLV = """\
# Generated by NetworkManager
nameserver 10.10.20.1
nameserver 10.10.20.53
search corp.example.internal example.internal
options edns0 trust-ad
"""

SYSTEMD_RESOLVED_STUB = """\
# This file is managed by man:systemd-resolved(8). DO NOT EDIT.
nameserver 127.0.0.53
search lan
options edns0 trust-ad
"""

NO_SEARCH = """\
nameserver 8.8.8.8
nameserver 8.8.4.4
"""

MALFORMED_RESOLV = """\
nameserver not-an-ip
nameserver 10.10.20.1
garbage line here
search
"""
